name: Studio Flourish
favicon: null
layout_spectrum: 0.30846
typography_spectrum: 0.974662
title: Studio Flourish
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#c9d6df'
    - '#95b7b8'
    - '#565c68'
  brandStrength: 0.875
  lightness: 0.6577829
  saturation: 0.6071042
  rhythmicContrast: 0.7022262
purpose: []
